### ISSUE TITLE
[RFC] Bareflank-LibVMI Hypercall ABI

### ISSUE THREAD

**Issue by boddumanohar** [boddumanohar/libvmi_extensions#1]
This RFC is a discussion of Bareflank-LibVMI hypercall ABI 

A request is made to hypervisor with a hypercall ID which will be  stored in `rax` register and the bareflank dispatches the task to the appropriate vmcall_handler based on hypercall ID. 

Some hypercalls, take some data as input while other return data output. To facilitate the this, `libvmi_extensions` create common shared memory region between hypervisor and LibVMI with read-write-execute permissions. When libvmi_extensions are loaded, the details of the shared memory(starting memory address with size) will be printed to output so the hypercall with data as input can use this region.  This shared memory with a fixed size will be created with Bareflank `memory_manager.h`. 

The JSON format will be used for input-output data. We can use any json parser create
the data on one side and retrive the data on the otherside. 

**When data is given as input to Hypervisor:**

the input data is first formated in the JSON format and then copied into the shared region. 
and get the size of the total data. 

The ABI for the hypercal looks like

```
mov rax 0x5          ; hypercall ID
mov rbx 0x2347789688 ;starting region of memory 
mov rcx 0x16         ;size of the input data

vmcall
```

**When data is given as output by the hypervisor:**

the output data is first formated in the JSON format and then copied into the shared region and get the size of the total data. 

The ABI for the hypercall looks like
```
mov rax 0x6 ; hypercall ID
vmcall      ; Give hypercall
            ; collect the size of the data returned in rcx register. 
```

This region can be used by memory mapping hypercall to map a process's memory into this region so that LibVMI can read from the region. 

Now the next immediate task is to create a shared memory region. I am thinking to create
a simple version of Xen's Grant table. So that this region can be shared with multiple VMs.

@rianquinn @connojd @tklengyel please comment your thoughts

**Comment by rianquinn** [comment]
is there a particular reason why JSON is being used for the ABI? JSON works great when a human has to fill in the information. Since this is code your adding to LibVMI, it would be a lot easier if you created a register based ABI, and just filled in each register as needed.

**Comment by boddumanohar** [comment]
My first idea was to use the register to exchange data. But in cases where I would like to know the state of all the registers, I cannot use the registers. And in some cases  size of the data could be more than 64 bits. For this reason, I choose to exchange data in the memory. In memory, using structs could lead to some problems with compiler vecause we use different compiler for Bareflank(clang) and LibVMI(gcc). So I thought an other structured way to exchange data would be JSON.

**Comment by cjams** [comment]
Personally I've never been a fan of having a JSON parser run in VMX-root. IMO, the ABI should use the bare-minimum required, and then more complex actions like "map this memory and parse it as JSON" built on top of the register-based ABI.

Is this ABI specific to libVMI? Or will this form the basis of the the entire PV interface?

**Comment by boddumanohar** [comment]
[[RFC] VMcall interface](https://github.com/Bareflank/hypervisor/issues/182) discusses a typical Bareflank hypercall ABI. The primary goal here is to exchange the kind of data that cannot simply fit into registers. So the Hypervisor should maintain a shared region to exchange such data. We create the shared region and provide the pointers to shared regions in the registers.

Along with that, this shared region could be used by memory mapping hypercalls. where we map a process's memory running in a guest VM into the shared memory so that libVMI can read mapped memory.

The PV interface will simply be an extension to the shared memory. PV interface should support interrupts too. So this shared memory + interrupts support together will be called as PV interface. 

@rianquinn @connojd @tklengyel do you have any suggestion on how data in this shared memory has to be formated other than JSON?

**Comment by rianquinn** [comment]
The shared memory buffer makes sense, but the rule of thumb should be, if it can fit in the registers, use the registers, if it doesn't fit in the registers, use a shared memory region, and define the data via in a struct. 

Also.... I would make sure that you don't use variable sized structures. Meaning, each struct that you need in the shared memory page should have a max size to improve safety, and allow you to keep the shared page mapped in at all times.

**Comment by tklengyel** [comment]
I'm not in favor of using C structures in the shared memory region. Xen did that and if you ask anyone working with it will tell you that it was a mistake. Using json would probably make our life easier even if that means having to include a json library into the hypervisor.
